apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtatoserver
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: podtatoserver
  template:
    metadata:
      labels:
        app: podtatoserver
      annotations:
        metrics.dynatrace.com/port: "9000"
        metrics.dynatrace.com/scrape: "true"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: podtatoserver
        image: "{{ .Values.image }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: PORT
          value: "9000"