apiVersion: v1
kind: Service
metadata:
  name: podtatoserver
  namespace: {{ .Release.Namespace }} 
spec:
  selector:
    app: podtatoserver
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  type: ClusterIP
