--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your_deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: your_service
  template:
    metadata: 
      labels:
        app: your_service
    spec:
      containers:
      - name: your_service
        image: "{{ .Values.image }}"